{% set name = "pymatgen-analysis-alloys" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymatgen_analysis_alloys-{{ version }}.tar.gz
  sha256: 972f8b902ca55a254301653fbceebc74b9939c03a6fb2a5f7a5ff607ac88b087

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pymatgen >=2023.7.17
    - shapely >=1.8.2

test:
  imports:
    - pymatgen.analysis.alloys
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/materialsproject/pymatgen-analysis-alloys
  summary: A pymatgen add-on library with classes useful for describing alloy (disordered) systems.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
